# Generated by Django 3.2.5 on 2022-02-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.CharField(max_length=36),
        ),
    ]
